# Aliases
alias bcl="brew cask list"
alias bsl="brew services list"
alias buu="brew update && brew upgrade && brew cleanup"
alias c="code ."
alias cdbit="cd ~/Repos/bitbucket.org"
alias cdhub="cd ~/Repos/github.com"
alias cdlab="cd ~/Repos/gitlab.com"
alias dc="docker-compose"
alias dcl="docker ps -a"
alias dcu="docker-compose up"
alias dnl="docker network ls"
alias dsp="docker system prune -af"
alias ga="git add ."
alias gc="git commit -n"
alias gca="git commit -n --amend --no-edit"
alias gcb="git checkout -b"
alias gcd="git checkout develop"
alias gcm="git checkout master"
alias gfo="git fetch origin develop:develop"
alias gfp="git push --force-with-lease"
alias gl="git log --graph --oneline --decorate"
alias gp="git pull"
alias gra="git rebase --abort"
alias grc="git rebase --continue"
alias grd="git rebase -i develop"
alias gs="git status"
alias gsl="git stash list"
alias gsp="git stash pop"
alias hc="history -c"
alias ll="ls -lah"
alias naf="npm audit fix"
alias ng="npm list -g --depth=0"
alias nrb="npm run build"
alias nrd="npm run dev"
alias nrs="npm run serve"
alias nrt="npm run test"
alias yg="yarn global list"

# Paths
export CPPFLAGS="-I/usr/local/opt/php@7.2/include"
export HOMEBREW_NO_ANALYTICS=1
export LDFLAGS="-L/usr/local/opt/php@7.2/lib"
export PATH="/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$PATH"
export PATH="/usr/local/opt/php@7.2/bin:$PATH"
export PATH="/usr/local/opt/php@7.2/sbin:$PATH"
export PATH="/usr/local/sbin:$PATH"
